### ISSUE TITLE
UTXO-sharing remains unproven, Prototyping standard to reject complexity

### ISSUE THREAD

**Issue by BitcoinErrorLog** [bitcoin-cap/bcap#25]
While not specified, I assume a large motivation of the people involved in this research are motivated to add complexity to Bitcoin, specifically more models for UTXO-sharing. It should be noted that this model remains unproven as a significant method for providing scale, with enormous tradeoffs that many users find unbearable. 

Proposals should be required to demonstrate their designs in real application prototypes, and/or on experimental blockchains before being taken seriously for Bitcoin because I think the many of the planned UX's are likely obnoxious shrines to complexity that barely scale without heaps of trust required.

**Comment by moneyball** [comment]
"I assume a large motivation of the people involved in this research are
motivated to add complexity to Bitcoin"

This assumption is false. The originators of the project have taken great
pains to be as neutral as possible with BCAP and that is an objective of
BCAP. BCAP isn't pro-ossification or pro-change. My own personal view is
"team slow and steady" which I've had in my X bio for the better part of
2024. The initial set of reviewers of this project ranged from very
conservative people to people who work for Taproot Wizards.

If you spot any framing or language which biases BCAP one way or another on
change philosophy, please point it out and it will be corrected.

As for UTXO sharing, you already state it isn't even mentioned in BCAP, so
this seems like a made up concern to me.

**Comment by moneyball** [comment]
> "If UTXO-sharing really is a dead end, then BCAP's current direction may need significant re-evaluation."

Again BCAP does not mention UTXO-sharing. It does not dependent upon UTXO-sharing. It is a project goal to be timeless so as to be useful in 10-20 years when whatever the consensus change du jour is.

This project is valuable even if there is never a consensus change again. It is important to analyze and understand how bitcoin does _not_ change.

> "The implication is that BCAP would need to pivot to a default position that is more about protecting existing stability and status quo, rather than exploring and narrating past habits of change, or taking speculative proposals seriously."

It is a fact change has happened in the past. Let's learn from the past instead of hiding from it. It is also possible that change could be attempted in the future. It is important for not only those who seek change but perhaps even more important for those who do not want change to understand various mechanisms people who want to change bitcoin may try. It would help you and others detect it early and if you don't like it you can voice that.

> "lack of whom I would consider to be conservative"

I'd say the majority of reviewers are conservative including me.

**Comment by BitcoinErrorLog** [comment]
Call me paranoid, but I simply do not believe the inspiration, participation, or creation of BCAP is in the interest of enforcing status quo or being conservative about Bitcoin change. 

Yes, it may exist as harmless historical research, but it also includes analysis and predictive templating of roles and powers, and other narratives. It is tolerant of Bitcoin governance and the ideas of speculative change and complexity.

My comments do not imply any sort of desire to hide from the past, merely a much more stark view on what actually happened and how to think about it. 

When change is attempted in the future, I want the people to be trained to know to reject it unless they personally NEED it, and to be extremely averse to new complexity and wild claims, to the point of everyone realizing a symptom/data-driven market demand approach is the only moral and safe method; that consensus cannot be "built" it can only be coerced or delivered.

> I'd say the majority of reviewers are conservative including me.

I'd say none of you have even crossed the center yet.

**Comment by moneyball** [comment]
Closing this issue as all I see in it is inaccurate speculation about BCAP. I don't see anything actionable.
